dist: focal

language: node_js

services:
  - docker

addons:
  apt:
    sources:
      - sourceline: 'deb https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable'
    packages:
      - docker.io

sudo: false

node_js:
  - "12"
  - "14"

install:
  - npm install
  - docker pull dashpay/tenderdash

script:
  - npm run lint && npm test
