dist: focal

language: node_js

services:
  - docker

addons:
  apt:
    packages:
      - docker-ce

sudo: false

node_js:
  - "12"
  - "14"

install:
  - npm install
  - docker pull dashpay/tenderdash

script:
  - npm run lint && npm test
